import './styles/globals.scss'
import type {Metadata} from 'next'
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ["400", "500", "700"],
})

export const metadata: Metadata = {
  title: 'React Weather App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
    <link rel="icon" href="/favicon.ico" sizes="any"/>
    <body className={montserrat.className}>{children}</body>
    </html>
  )
}
