import './styles/globals.scss'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'React Weather App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
    <link rel="icon" href="/favicon.ico" sizes="any"/>
    <body>{children}</body>
    </html>
  )
}
